--        PROJECT 3: METRICS & AGGREGATION QUERY SCRIPT

-- Retrieve the first 10 rows to verify all clean columns and metrics are present
SELECT * 
FROM `decode labs dataset` 
LIMIT 10;

-- Filter transactions where the product quantity sold is 5 or more
SELECT Cleaned_Order_ID, Cleaned_Customer_ID, Cleaned_Products, Quantity, UnitPrice 
FROM `decode labs dataset`
WHERE Quantity >= 5;

-- Calculate the total number of orders and the total overall revenue generated
SELECT 
    COUNT(Cleaned_Order_ID) AS Total_Orders,
    SUM(Quantity * UnitPrice) AS Total_Revenue
FROM `decode labs dataset`;

-- Group sales data by product to calculate total units sold and revenue per item
-- The result is sorted in descending order to identify the top-performing products
SELECT 
    Cleaned_Products AS Product,
    SUM(Quantity) AS Total_Units_Sold,
    SUM(Quantity * UnitPrice) AS Revenue_Generated
FROM `decode labs dataset`
GROUP BY Product
ORDER BY Revenue_Generated DESC;

-- Calculate the average spending per transaction across the dataset
SELECT 
    AVG(Quantity * UnitPrice) AS Average_Order_Value
FROM `decode labs dataset`;

-- Identify Top Spenders (Customer Insights)
-- Group by customer ID to find the total revenue generated by each individual customer
-- Sorted in descending order to highlight the highest-spending customers
SELECT 
    Cleaned_Customer_ID AS Customer_ID,
    COUNT(Cleaned_Order_ID) AS Total_Orders_Placed,
    SUM(Quantity * UnitPrice) AS Total_Amount_Spent
FROM `decode labs dataset`
GROUP BY Cleaned_Customer_ID
ORDER BY Total_Amount_Spent DESC
LIMIT 10;

-- Conditional Analytics using HAVING (High-Value Products Only)
-- Aggregate sales by product but only display products that cross a specific revenue threshold
-- This helps management focus on high-performing product categories
SELECT 
    Cleaned_Products AS Product_Name,
    SUM(Quantity * UnitPrice) AS Total_Revenue
FROM `decode labs dataset`
GROUP BY Cleaned_Products
HAVING Total_Revenue > 5000
ORDER BY Total_Revenue DESC;

-- Multi-Level Sorting (Quantity and Price Analysis)
-- Retrieve transactions sorted primarily by the largest quantity sold, 
-- and secondarily by the highest unit price to analyze bulk purchasing patterns
SELECT Cleaned_Order_ID, Cleaned_Products, Quantity, UnitPrice
FROM `decode labs dataset`
ORDER BY Quantity DESC, UnitPrice DESC
LIMIT 20;